name: Daily Stock Check

on:
 schedule:
  cron: '08***'
  workflow_dispatch:

  jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run stock script
      run: python main.py

    - name: Upload Excel Result
      uses: actions/upload-artifact@v3
      with:
        name: stock-report
        path: stock_analysis_trial.xlsx
