name: daily-stock

on:
  schedule:
    -cron: '30 7 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run:  pip install yfinance pandas openpyxl

      - name: Run script
        run: python trial.py

      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: stock-report
          path: my_stocks.xlsx
